### ISSUE TITLE
Como Jugador quiero un bucle de juego

### ISSUE THREAD

**Issue by DanielZhu26** [UCM-FDI-DISIA/FuMonoStudios#17]
El juego tiene menú inicial escena de juego y se puede cerrar
La clase generaldata funciona bien su singleton
Solucionaron los problemas del callback de los botones al ejecutar el cambio de escena en ellos

**Comment by Adelpozo04** [comment]
Esta tarea debe de ser ampliada y explorada más haya en un futuro, aunque si es posible mantener tan solo un id del final principal, para los eventos se debería usar un vector o cola ya que estos eventos pueden acumularse segun con cuantos npcs hables en la fase de exploración. Por lo demás todo funciona correctamente.
