### ISSUE TITLE
Feedback saber a que tubería vas a meter el paquete

### ISSUE THREAD

**Issue by miguelNPB** [UCM-FDI-DISIA/FuMonoStudios#186]

**Comment by miguelNPB** [comment]
Esto conlleva hacer el sistema animaciones

**Comment by LuisEnriqueCabelloBlanco** [comment]
Se puede aprovechar lo que esté hecho de #199

**Comment by LuisEnriqueCabelloBlanco** [comment]
- [ ] Crear un hover detector para que se lancen callbacks al pasar el cursor por encima del transform o si una entidad de cierta capa está haciendo overlap
