### ISSUE TITLE
Sonidos diferentes para cada objeto en la oficina

### ISSUE THREAD

**Issue by PablooMS** [UCM-FDI-DISIA/FuMonoStudios#288]
Necesitaremos al menos tres sonidos de cada, para variar un poco, EXCEPTO en los de arrastrar, en los cuales solo querremos uno (ya que hay problemas al borrar)
- [ ] Sonido de libro (sobre madera y arrastrar)
~~Sonido diferentes para cada tipo de caja~~
- [x] Sonidos para el sellador (ambos para cuando cae y cuando sella, y estaría bien unos para cuando cambia de color)
- [x] Sonidos para el embalador (ambos para cuando cae y cuando está siendo utilizado)
- [x] Sonidos para el reloj cuando se va acercando al final
- [x] Sonidos para las tuberías al absorber un paquete

También estaría bien diferentes sonidos para diferentes tipos de paquetes, pero eso podría ser otra historia de usuario

**Comment by JulianSerranoChacon** [comment]
https://www.soundsnap.com/hardcover_book_pages_turn_blastwavefx_22791  para el sonido de pasar de página

**Comment by JulianSerranoChacon** [comment]
https://www.soundsnap.com/body_drag_on_farmlane_01_02_wav para arrastrar el libro

**Comment by PablooMS** [comment]
"musics": [
  {
    "id": "trabajo",
    "file": "recursos/sounds/imperial_march.wav"
  },
  {
    "id": "mainMenu",
    "file": "recursos/sounds/DQOverture.wav"
  },
  {
    "id": "office",
    "file": "recursos/sounds/office.wav"
  },
  {
    "id": "printer",
    "file": "recursos/sounds/printer.wav"
  }
]

**Comment by PablooMS** [comment]
CAJAS SERÁN NICE TO HAVE
