### ISSUE TITLE
Sello frágil y mecánica embalado

### ISSUE THREAD

**Issue by LuisEnriqueCabelloBlanco** [UCM-FDI-DISIA/FuMonoStudios#64]

**Comment by Adelpozo04** [comment]
La base de la mecanica y mayor parte de la programación esta hecha, falta la representacion de que algo esta ya enbalado y de en que % esta hecho, sin embargo debido al peso de eso lo dejaria como otra historia de usuario y le bajaria el peso a esta, para tener historias más divididas
